### ISSUE TITLE
Warning: find_unused_parameters=True was specified in DDP constructor...

### ISSUE THREAD

**Issue by jxtps** [cszn/KAIR#103]
When I train SwinIR using KAIR & the supplied options file I get the following warning: 

```
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. 
This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. 
If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. 
Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
```

Reviewing the `network_swinir.py` code there are indeed a bunch of if-statements in the `def forward()` methods, but these seem to not change from batch to batch. 

Can I set `find_unused_parameters=False`, or is there some pitfall here? Thanks!

**Comment by JingyunLiang** [comment]
I think it is safe to try `find_unused_parameters=False`. It should not result in any problems.

**Comment by jxtps** [comment]
Thanks! It seems to be working fine, but also had no measurable performance impact on training speed.
