### ISSUE TITLE
Thanks to the author’s KAIR，But...

### ISSUE THREAD

**Issue by QiuPaul** [cszn/KAIR#107]
Thanks to the author’s KAIR, many techniques for image restoration are very impressive. But for some extreme real-world images: noise + blur + deformation(Many degradation factors at the sam time), the presented technology cannot solve very well, however we human can make up for it in our brain. How much can CV restorate? in what manner？Because I always believe in a promising CV recovery technology：the restoration  equals secondary creation.

**Comment by JingyunLiang** [comment]
It's an interesting question. Our goal is to restore images like human. Actually, the training process is like gaining knowledge of prior knowledge, but there is no explicit inference as human can do. It's a common problem of existing learning-based methods.

**Comment by QiuPaul** [comment]
你好，邮件已收到，我会尽快给您回复..  谢谢！！！

**Comment by QiuPaul** [comment]
你好，邮件已收到，我会尽快给您回复..  谢谢！！！
