### ISSUE TITLE
Cannot reproduce SwinIR results

### ISSUE THREAD

**Issue by Pexure** [cszn/KAIR#108]
Dear authors,
I ran SwinIR classical super-resolution with `python -m torch.distributed.launch --nproc_per_node=8 --master_port=1234 main_train_psnr.py --opt options/swinir/train_swinir_sr_classical.json  --dist True`, and add test code in it. But the final result for Set5 is 38.25~38.26, which is 0.1 dB lower than reported in Table2 in the paper.

![image](https://user-images.githubusercontent.com/47890443/145743904-3df61f5d-5f51-4995-931c-25c5936a540f.png)

Do you have any ideas about it?
Thanks!

**Comment by Pexure** [comment]
and here is the config

21-12-10 12:07:10.739 :   task: swinir_sr_classical_patch48_x2
  model: plain
  gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  dist: True
  scale: 2
  n_channels: 3
  path:[
    root: superresolution
    pretrained_netG: None
    pretrained_netE: None
    task: superresolution/swinir_sr_classical_patch48_x2
    log: superresolution/swinir_sr_classical_patch48_x2
    options: superresolution/swinir_sr_classical_patch48_x2/options
    models: superresolution/swinir_sr_classical_patch48_x2/models
    images: superresolution/swinir_sr_classical_patch48_x2/images
    pretrained_optimizerG: None
  ]
  datasets:[
    train:[
      name: train_dataset
      dataset_type: sr
      dataroot_H: /mnt/cfs/algorithm/public_data/SR/DIV2K/DIV2K_train_HR_sub
      dataroot_L: /mnt/cfs/algorithm/public_data/SR/DIV2K/DIV2K_train_LR_bicubic/X2_sub
      H_size: 96
      dataloader_shuffle: True
      dataloader_num_workers: 16
      dataloader_batch_size: 32
      phase: train
      scale: 2
      n_channels: 3
    ]
    test:[
      name: test_dataset
      dataset_type: sr
      dataroot_H: /mnt/cfs/algorithm/public_data/SR/test/Set5/GTmod12
      dataroot_L: /mnt/cfs/algorithm/public_data/SR/test/Set5/LRbicx2
      phase: test
      scale: 2
      n_channels: 3
    ]
  ]
  netG:[
    net_type: swinir
    upscale: 2
    in_chans: 3
    img_size: 48
    window_size: 8
    img_range: 1.0
    depths: [6, 6, 6, 6, 6, 6]
    embed_dim: 180
    num_heads: [6, 6, 6, 6, 6, 6]
    mlp_ratio: 2
    upsampler: pixelshuffle
    resi_connection: 1conv
    init_type: default
    scale: 2
  ]
  train:[
    G_lossfn_type: l1
    G_lossfn_weight: 1.0
    E_decay: 0.999
    G_optimizer_type: adam
    G_optimizer_lr: 0.0002
    G_optimizer_wd: 0
    G_optimizer_clipgrad: None
    G_optimizer_reuse: True
    G_scheduler_type: MultiStepLR
    G_scheduler_milestones: [250000, 400000, 450000, 475000, 500000]
    G_scheduler_gamma: 0.5
    G_regularizer_orthstep: None
    G_regularizer_clipstep: None
    G_param_strict: True
    E_param_strict: True
    checkpoint_test: 10
    checkpoint_save: 50000
    checkpoint_print: 10
    F_feature_layer: 34
    F_weights: 1.0
    F_lossfn_type: l1
    F_use_input_norm: True
    F_use_range_norm: False
  ]
  opt_path: options/swinir/train_swinir_sr_classical_x2.json
  is_train: True
  merge_bn: False
  merge_bn_startpoint: -1
  find_unused_parameters: True
  num_gpu: 8
  rank: 0
  world_size: 8

21-12-10 12:07:11.124 : Number of train images: 32,592, iters: 1,019
21-12-10 12:07:19.123 : 
Networks name: SwinIR
Params number: 11752487
Net structure:
SwinIR(
   .......
)

**Comment by JingyunLiang** [comment]
Can you try to test your model with codes from [SwinIR](https://github.com/JingyunLiang/SwinIR)? What about its performance on other testing sets?

**Comment by Pexure** [comment]
I test with `python main_test_swinir.py --task classical_sr --scale 2 --training_patch_size 48 --model_path superresolution/swinir_sr_classical_patch48_x2/models/500000_G.pth --folder_lq /path/to/Set5(14)/LRbicx2 --folder_gt /path/to/Set5(14)/GTmod12`, and got the following results.

Set5:
![image](https://user-images.githubusercontent.com/47890443/145923511-a8816c15-99c6-4e2a-b501-a77d395d3562.png)

Set14:
![image](https://user-images.githubusercontent.com/47890443/145923486-cf74f01b-7444-4c84-b18d-5cae7a3432db.png)

As I didn't find the instruction to prepare Set5/14 in this repo, I used the test sets provided by [BasicSR](https://github.com/xinntao/BasicSR).

Set5 is a bit higher than tested at training as shown above. I wonder what makes the difference?

**Comment by JingyunLiang** [comment]
I think it's due to border cropping and slightly different in SSIM implementation.

**Comment by Pexure** [comment]
I think I have got the reason. The test code in `main_train_psnr.py` is inconsistent with that in `main_test_swinir.py`.

In `main_train_psnr.py`, PSNR is tested on output and gt with order HWC-RGB, 
https://github.com/cszn/KAIR/blob/608112e6fb8129cffd0af1d10b33a568af9206ab/main_train_psnr.py#L223-L236
while in `main_test_swinir.py`, PSNR/SSIM is tested on two tensors of HWC-BGR. This makes the gap of ~0.05 dB.

By the way, even if I test with `main_test_swinir.py`, the PSNR_Y for Set5 is still ~0.05 dB lower than reported (38.30 vs 38.35), which I think is nontrivial considering the gap between SwinIR and other methods for comparison. Is this within the reasonable training variance (e.g., random seeds)?

**Comment by JingyunLiang** [comment]
I think it's due to randomness. After all, Set5 only has 5 images. What about your results on other 4 datasets? For example, I saw that your PSNR on Set14 is even better than mine.

**Comment by Pexure** [comment]
Could you tell me how to make the lq folder for BSDS100, Urban100 and Manga109? It's required by `main_test_swinir.py`.

**Comment by JingyunLiang** [comment]
See https://github.com/cszn/KAIR/blob/master/docs/README_SwinIR.md#dataset-preparation

**Comment by Pexure** [comment]
Thanks.

**Comment by Zency-Sun** [comment]
感谢前辈们精彩的工作。
最近我在验证前辈的代码时，使用一块3090显卡，训练classicalSRx2，训练了1Kepoch，随后使用训练好的模型验证的结果是：38.06，请问是由于我的训练轮数太少吗？还是因为其他原因？请赐教！
`/bin/bash /media/zency/SSD-Data/KAIR-1.1/run.sh
loading model from /media/zency/SSD-Data/SwinIR_result/3_Swinx2_1000epoch_[500,800,900,950]/models/50000_G.pth
Testing 0 baby                 - PSNR: 37.38 dB; SSIM: 0.9601; PSNR_Y: 38.92 dB; SSIM_Y: 0.9679; PSNR_B: 0.00 dB.
Testing 1 bird                 - PSNR: 40.57 dB; SSIM: 0.9839; PSNR_Y: 43.26 dB; SSIM_Y: 0.9905; PSNR_B: 0.00 dB.
Testing 2 butterfly            - PSNR: 33.87 dB; SSIM: 0.9712; PSNR_Y: 35.48 dB; SSIM_Y: 0.9789; PSNR_B: 0.00 dB.
Testing 3 head                 - PSNR: 32.32 dB; SSIM: 0.8340; PSNR_Y: 36.06 dB; SSIM_Y: 0.8920; PSNR_B: 0.00 dB.
Testing 4 woman                - PSNR: 35.21 dB; SSIM: 0.9715; PSNR_Y: 36.59 dB; SSIM_Y: 0.9752; PSNR_B: 0.00 dB.

results/swinir_classical_sr_x2 
-- Average PSNR/SSIM(RGB): 35.87 dB; 0.9442
-- Average PSNR_Y/SSIM_Y: 38.06 dB; 0.9609
`
以下是配置情况
`23-02-25 17:12:25.762 :   task: swinir_sr_classical_patch48_x2
  model: plain
  gpu_ids: [0]
  dist: False
  scale: 2
  n_channels: 3
  path:[
    root: superresolution
    pretrained_netG: None
    pretrained_netE: None
    task: superresolution/swinir_sr_classical_patch48_x2
    log: superresolution/swinir_sr_classical_patch48_x2
    options: superresolution/swinir_sr_classical_patch48_x2/options
    models: superresolution/swinir_sr_classical_patch48_x2/models
    images: superresolution/swinir_sr_classical_patch48_x2/images
    pretrained_optimizerG: None
  ]
  datasets:[
    train:[
      name: train_dataset
      dataset_type: sr
      dataroot_H: /media/zency/SSD-Data/Dataset/DIV2K/DIV2K_train_HR
      dataroot_L: /media/zency/SSD-Data/Dataset/DIV2K/DIV2K_train_LR_bicubic/X2
      H_size: 96
      dataloader_shuffle: True
      dataloader_num_workers: 16
      dataloader_batch_size: 16
      phase: train
      scale: 2
      n_channels: 3
    ]
    test:[
      name: test_dataset
      dataset_type: sr
      dataroot_H: testsets/Set5/HR
      dataroot_L: testsets/Set5/LR_bicubic/X2
      phase: test
      scale: 2
      n_channels: 3
    ]
  ]
  netG:[
    net_type: swinir
    upscale: 2
    in_chans: 3
    img_size: 48
    window_size: 8
    img_range: 1.0
    depths: [6, 6, 6, 6, 6, 6]
    embed_dim: 180
    num_heads: [6, 6, 6, 6, 6, 6]
    mlp_ratio: 2
    upsampler: pixelshuffle
    resi_connection: 1conv
    init_type: default
    scale: 2
  ]
  train:[
    G_lossfn_type: l1
    G_lossfn_weight: 1.0
    E_decay: 0.999
    G_optimizer_type: adam
    G_optimizer_lr: 0.0002
    G_optimizer_wd: 0
    G_optimizer_clipgrad: None
    G_optimizer_reuse: True
    G_scheduler_type: MultiStepLR
    G_scheduler_milestones: [500, 800, 900, 950, 1000]
    G_scheduler_gamma: 0.5
    G_regularizer_orthstep: None
    G_regularizer_clipstep: None
    G_param_strict: True
    E_param_strict: True
    checkpoint_test: 50
    checkpoint_save: 50
    checkpoint_print: 50
    F_feature_layer: 34
    F_weights: 1.0
    F_lossfn_type: l1
    F_use_input_norm: True
    F_use_range_norm: False
  ]
  opt_path: options/swinir/train_swinir_sr_classical.json
  is_train: True
  merge_bn: False
  merge_bn_startpoint: -1
  find_unused_parameters: True
  num_gpu: 1
  rank: 0
  world_size: 1

23-02-25 17:12:25.769 : Number of train images: 800, iters: 50
23-02-25 17:12:27.031 : 
Networks name: SwinIR
Params number: 11752487
Net structure:`
@JingyunLiang @Pexure
