### ISSUE TITLE
training image size error

### ISSUE THREAD

**Issue by EvelyneCalista** [cszn/KAIR#112]
hi, i  am new in this field.

I tried to reproduce with custom dataset but got this error below,

i already tried to crop with fix number, but not solved the error.

_RuntimeError: stack expects each tensor to be equal size, but got [3, 48, 48] at entry 0 and [3, 47, 43]_ 

i am confuse, where this error comes from.
thank you.

**Comment by JingyunLiang** [comment]
In random cropping, some patches are less than 48x48. Possibly they are close to the down-right of the original image.
