### ISSUE TITLE
Question about training USRNet

### ISSUE THREAD

**Issue by 1144181135** [cszn/KAIR#115]
Hello,
    I have some questions about training USRNet. 
    When I read the training code, I can not find where the optimization of equation 5 and 6. In the lines 149-152 of
 [https://github.com/cszn/KAIR/blob/master/models/model_plain.py](url), it seems that only l1 loss and conventional backward are used in the code. Can you point out the part in which the optimization of equation 5 and 6?
    Thank you!

**Comment by cszn** [comment]
https://github.com/cszn/KAIR/blob/72e93351bca41d1b1f6a4c3e1957f5bffccc7101/models/network_usrnet_v1.py#L228

**Comment by zengyi319** [comment]
Thank you Kai Zhang. I have another question about training dpsr [https://arxiv.org/pdf/2008.13751.pdf](url).  About the optimization of eq. 6a and 6b, in the Algorithm 1, it seems that K iterations are in each training sample. However, I can not find the code for K iterations in neither models/network_dpsr.py or models/model_plain.py, Can you point out the part in which the optimization of eq. 6a and 6b ( K iterations in Algorithm 1 )? Thank you !

>

**Comment by zengyi319** [comment]
> Thank you Kai Zhang. I have another question about training dpsr [https://arxiv.org/pdf/2008.13751.pdf](url). About the optimization of eq. 6a and 6b, in the Algorithm 1, it seems that K iterations are in each training sample. However, I can not find the code for K iterations in neither models/network_dpsr.py or models/model_plain.py, Can you point out the part in which the optimization of eq. 6a and 6b ( K iterations in Algorithm 1 )? Thank you !

**Comment by cszn** [comment]
https://github.com/cszn/DPSR/blob/a5aa2728504b21c1585ef5983bf67db273b10736/demo_test_dpsr.py#L192
