### ISSUE TITLE
main_train_ffdnet.py missing

### ISSUE THREAD

**Issue by amonod** [cszn/KAIR#123]
Hello,

The main python script file to train ffdnet with pytorch (also referenced to in [https://github.com/cszn/FFDNet](https://github.com/cszn/FFDNet)) is missing.
Going to [https://github.com/cszn/KAIR/blob/master/main_train_ffdnet.py](https://github.com/cszn/KAIR/blob/master/main_train_ffdnet.py) leads to a 404.

Is that normal?

**Comment by MediocrityXT** [comment]
I found this. [main_train_ffdnet.py](https://github.com/lewishaas/KAIR/blob/master/main_train_ffdnet.py) 
I guess author slightly edited and renamed the main_train_ffdnet.py to main_train_drunet.py

**Comment by cszn** [comment]
Run
`python main_train_psnr.py --opt options/train_ffdnet.json`
