### ISSUE TITLE
 The paging file is too small for this operation to complete.

### ISSUE THREAD

**Issue by YildizzEmrah** [cszn/KAIR#127]
Hello, I got this error so ı dont understand why this error comes to me. 

OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "D:\Anaconda\envs\swin-train\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

This is my option settings.
and ı run with console this line 

python main_train_psnr.py --opt options/swinir/train_swinir_sr_classical.json

![Adsız](https://user-images.githubusercontent.com/90452717/159191740-4edaa02e-d927-47e0-9057-2622419ce646.jpg)
I got 2 gpu , 1080ti gpu 0 and gpu 1 .

Please somene one can help me ? I want to train my own dataset whit swinir

**Comment by wwhio** [comment]
IMO, it's your system memoery issue. 
Try to reduce `dataloader_num_workers` may be useful. 
Or, you can try to change `pin_memory=False` for DataLoader [here](https://github.com/cszn/KAIR/blob/6b059c19bbf15dc7f90f6ffef12eee10e6a5b28e/main_train_psnr.py#L131) and [here](https://github.com/cszn/KAIR/blob/6b059c19bbf15dc7f90f6ffef12eee10e6a5b28e/main_train_psnr.py#L139).

**Comment by JingyunLiang** [comment]
Thank you @wwhio
