### ISSUE TITLE
training speed about swinir

### ISSUE THREAD

**Issue by caopulan** [cszn/KAIR#129]
This problem has been issued in SwinIR. https://github.com/JingyunLiang/SwinIR/issues/81#issue-1190556573
I have profiled training process, loading data costs 0.2s/iter and "model.optimize_parameters(current_step)" costs 0.5s.
Even though the cost of data loading is ignored, my training process will cost 3 days.

**Comment by JingyunLiang** [comment]
If you meet I/O bottleneck, preparing the dataset as lmdb (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/create_lmdb.py) or extracting them as small patches (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/extract_subimages.py) can help a lot. The PSNR performance will the same.
