### ISSUE TITLE
Training Datasets for VRT

### ISSUE THREAD

**Issue by ArfaSaif** [cszn/KAIR#131]
I'm running `main_train_vrt.py` and would like to use the default dataset used in the options.json file. Where can I find the lmdb files for the GT and the low resolution/low-quality images, or is there a way to recreate these files using the REDS dataset?

`'dataroot_gt': 'trainsets/REDS/train_sharp_with_val.lmdb', 'dataroot_lq': 'trainsets/REDS/train_sharp_bicubic_with_val.lmdb'`

thanks

**Comment by ArfaSaif** [comment]
I tried the dataset preparation steps from : https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md on the REDS dataset, and was able to create the lmdb files but I'm now getting this error when running the training loop: 
![image](https://user-images.githubusercontent.com/48233453/164748118-3f0bc750-353c-426c-83ec-c5ee403c9222.png)

**Comment by NasrinR791** [comment]
Hi @ArfaSaif 
I got the same error, did you fix it?

**Comment by ArfaSaif** [comment]
Hi @NasrinR791,
I followed the data preparation steps from here: https://github.com/XPixelGroup/BasicSR/blob/master/docs/DatasetPreparation.md

**Comment by ArfaSaif** [comment]
> Hi @ArfaSaif I got the same error, did you fix it?

Hi @NasrinR791, no not yet, I just ended up using the .png datasets instead of the .lmdb

**Comment by NasrinR791** [comment]
@ArfaSaif 

running python scripts/data_preparation/create_lmdb.py --dataset reds using raw REDS dataset solved my problem.

**Comment by JingyunLiang** [comment]
Thank you @NasrinR791

**Comment by jiamingNo1** [comment]
> @ArfaSaif
> 
> running python scripts/data_preparation/create_lmdb.py --dataset reds using raw REDS dataset solved my problem.

how to use the lmdb file? I review the code, find that there is not lmdb file decoding code in the project

**Comment by haoemo** [comment]
> I tried the dataset preparation steps from : https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md on the REDS dataset, and was able to create the lmdb files but I'm now getting this error when running the training loop: ![image](https://user-images.githubusercontent.com/48233453/164748118-3f0bc750-353c-426c-83ec-c5ee403c9222.png)

python scripts/data_preparation/regroup_reds_dataset.py    ---> ok

python scripts/data_preparation/create_lmdb.py --dataset reds   ---> ok

python main_train_vrt.py  --> still get this error 

So I try to figure out why it happens?

**Comment by cshuisui** [comment]
> > I tried the dataset preparation steps from : https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md on the REDS dataset, and was able to create the lmdb files but I'm now getting this error when running the training loop: ![image](https://user-images.githubusercontent.com/48233453/164748118-3f0bc750-353c-426c-83ec-c5ee403c9222.png)
> 
> python scripts/data_preparation/regroup_reds_dataset.py ---> ok
> 
> python scripts/data_preparation/create_lmdb.py --dataset reds ---> ok
> 
> python main_train_vrt.py --> still get this error
> 
> So I try to figure out why it happens?

Hi @haoemo , I have encountered the same problem, may I ask how you solved it. Thank you.
