### ISSUE TITLE
I have a question about netE

### ISSUE THREAD

**Issue by WateverOk** [cszn/KAIR#142]
I saw netE used for EMA in the process of reading the source code, but it seems that the result of EMA is useless. 
Training and testing have also been using netG for calculation. What is the role of netE？

**Comment by cszn** [comment]
https://github.com/cszn/KAIR/blob/06bd194f4cd0da6f4159c058b6fb5b9be689c18a/options/train_msrresnet_psnr.json#L62

set 0 to remove netE

**Comment by WateverOk** [comment]
> https://github.com/cszn/KAIR/blob/06bd194f4cd0da6f4159c058b6fb5b9be689c18a/options/train_msrresnet_psnr.json#L62
> 
> set 0 to remove netE

What is the role of netE if netE is not removed? Because it seems that netE is not used in the later tests.
