### ISSUE TITLE
DNCNN for SISR upscaling

### ISSUE THREAD

**Issue by tomvdon** [cszn/KAIR#155]
If I wanted to use the DNCNN network to upscale an image what would I need to change? After a lot of modifications I'm getting `RuntimeError: The size of tensor a (20) must match the size of tensor b (40) at non-singleton dimension 3` 
I'm supplying my own L and H images using the plain dateset and want to use DNCNN to have a lighter fully conv network.

**Comment by vegetableclean** [comment]
hi, could you tell me how to fix this, same problem here @tomvdon
