### ISSUE TITLE
DPSR Training Error

### ISSUE THREAD

**Issue by richardminh** [cszn/KAIR#18]
Thanks for @cszn contribution, DPSR is an amazing job.
I was tried to train with my own dataset with main_train_dpsr.py by using pretrained_netG.
I used pretrained_netG with dpsr repository's model, DPSRx4.pth.
But i got runtime error.
RuntimeError: Error(s) in loading state_dict for SRResNet:
        Missing key(s) in state_dict: "model.3.weight", "model.3.bias", "model.6.weight", "model.6.bias".
        Unexpected key(s) in state_dict: "model.2.weight", "model.2.bias", "model.5.weight", "model.5.bias".

How can i fix? Hope your kind help. Thanks

**Comment by cszn** [comment]
Make sure the network architectures are same.

Otherwise, you can fix the problem of parameter name mismatch via

```python
    net_old = torch.load('net_old.pth')
    def show_kv(net):
        for k, v in net.items():
            print(k)

    show_kv(net_old)
    from models.network_dpsr import MSRResNet_prior as net
    model = net(in_nc=4, out_nc=3, nc=96, nb=16, upscale=4, act_mode='R', upsample_mode='pixelshuffle')
    state_dict = network.state_dict()
    net_new = OrderedDict()
    for ((key, param),(key_old, param_old)) in zip(state_dict.items(), net_old.items()):
        net_new[key] = param_old
    torch.save(net_new, 'net_new.pth') 


```

**Comment by richardminh** [comment]
Thanks very much, I will try.

**Comment by richardminh** [comment]
The code working well now, Thanks very much. As more as i see this project, i realized that this project is great.
By the way, can you explain about the training model and procedures?
Of course, i saw your paper and i can't understand. 
Can you show me model construction with images?
Can you share the commented training code?
Thanks again.

**Comment by cszn** [comment]
https://github.com/cszn/KAIR/blob/master/main_train_dpsr.py

**Comment by richardminh** [comment]
thanks for your answer. But what is difference of dpsr &Kair's model?
I think two model seems to same structure.
