### ISSUE TITLE
model.init_train()  should be called before logger.info()

### ISSUE THREAD

**Issue by tabetomo** [cszn/KAIR#2]
Hi,

Your software is interesting. By the way,
In training, an error no attribute 'opt_train' occured, it seems the reason is logger.info() is called before model.init_train() . We should call model.init_train() before logger.info().

```
# orig order
   logger.info(model.info_network()) 
   model.init_train()   # this should be called before logger.info
   logger.info(model.info_params()) 
# fixed
   model.init_train() 
   logger.info(model.info_network()) 
   logger.info(model.info_params()) 
```

The error log is
```
Traceback (most recent call last):
  File "main_train_msrresnet_gan.py", line 224, in <module>
    main()
  File "main_train_msrresnet_gan.py", line 128, in main
    logger.info(model.info_network())
  File "/work/s124087/KAIR/models/model_gan.py", line 297, in info_network
    if self.opt_train['F_lossfn_weight'] > 0:
AttributeError: 'ModelGAN' object has no attribute 'opt_train'
```

Also I encountered the following warning.
> /usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate

**Comment by cszn** [comment]
Thanks. I have corrected it. 

You can safely use the scheduler as it takes ```current_step``` as input to update the learning rate in each iteration.
https://github.com/cszn/KAIR/blob/0e2fb11d8818c79a617db8a94b079cf5259148b7/main_train_msrresnet_gan.py#L146
https://github.com/cszn/KAIR/blob/0e2fb11d8818c79a617db8a94b079cf5259148b7/models/model_base.py#L61
