### ISSUE TITLE
Dear，sir. After I complete the SRMD model training, Indexerror is displayed in the test

### ISSUE THREAD

**Issue by cuican-0521** [cszn/KAIR#23]
After I complete the SRMD model training, Index error is displayed in the test。
But when I load the trained model online（srmd_×2，×3，×4）, no error occurs.
If you can help me, I will be particularly grateful！

**Comment by cszn** [comment]
Replace `srmd_×2.pth` with your new model or set new `model_path` and `sf`.

**Comment by cuican-0521** [comment]
Thanks for your reply. After the operation according to your guide,i have solved the problem. Thanks again.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Kai&amp;nbsp;Zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月5日(星期天) 下午5:02
收件人:&nbsp;&quot;cszn/KAIR&quot;<KAIR@noreply.github.com&gt;;
抄送:&nbsp;&quot;cuican-0521&quot;<646788757@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cszn/KAIR] Dear，sir. After I complete the SRMD model training, Indexerror is displayed in the test (#23)
