### ISSUE TITLE
util.tensor2uint: It takes a lot of time to convert GPU tensor to CPU tensor

### ISSUE THREAD

**Issue by LHJ1098826475** [cszn/KAIR#29]
Hi, I successfully run the test code of FFDNet. But I find it takes a lot of time (4.5s) to convert GPU tendor to CPU tensor and convert to uint8 image. Can you help me solve the problem. Thanks.

![image](https://user-images.githubusercontent.com/46620678/89246884-a901b800-d63e-11ea-8fc4-67549b4ac6a0.png)
![image](https://user-images.githubusercontent.com/46620678/89246905-b5861080-d63e-11ea-852a-90f9f8f9e80d.png)

**Comment by cszn** [comment]
To test the runtime, you should use the code as follows:
```python
torch.cuda.synchronize()
start = time.time()
img_E = util.tensor2uint(img_E)
torch.cuda.synchronize()
end = time.time()
```
