### ISSUE TITLE
USRNET training

### ISSUE THREAD

**Issue by Zepharchit** [cszn/KAIR#31]
Hi I am a beginner with Super Resolution task I was trying the usrnet.py as given in the repo, I created a similar .json file for usrnet by taking hints from other models. I am having issue with the training. Please provide directions on how to train the model correctly.
![Screenshot from 2020-08-21 17-39-40](https://user-images.githubusercontent.com/51807559/91126295-48a3ea80-e6c1-11ea-9108-3bf20f9f196b.png)

**Comment by lewishaas** [comment]
Creating the json and the training file should be all you need. Hard to tell what's going wrong without any of the code or json you added, but from the error message it seems like you might have `nc` as an integer.

**Comment by cszn** [comment]
@Zepharchit 

```python
{
  "task": "usrnet" //  
  , "model": "plain4" // "plain" | "gan"
  , "gpu_ids": [0]
  , "scale": 4
  , "n_channels": 3 // 1 for grayscale image restoration, 3 for color image restoration
  , "merge_bn": false
  , "merge_bn_startpoint": 300000

  , "datasets": {
    "train": {
      "name": "train_dataset"
      , "dataset_type": "usrnet"
      , "dataroot_H": "trainsets/trainH"
      , "dataroot_L": null
      , "H_size": 96 // 128 | 192
      , "use_flip": true
      , "use_rot": true
      , "scales": [1, 2, 3, 4]
      , "dataloader_shuffle": true
      , "dataloader_num_workers": 8
      , "dataloader_batch_size": 48
    }
    , "test": {
      "name": "test_dataset"
      , "dataset_type": "usrnet"
      , "dataroot_H": "testsets/set5"
      , "dataroot_L": null
    }
  }

  , "path": {
    "root": "SR"
    , "pretrained_netG": null
  }

  , "netG": {
    "netG_type": "usrnet" // "srresnet" | "rrdbnet" | "rcan" | "unet" | "unetplus" | "nonlocalunet"
    , "n_iter": 6
    , "in_nc": 4
    , "out_nc": 3
    , "nc": [16, 32, 64, 64] // [64, 128, 256, 512] for "unet"
    , "nb": 2 // 16 for "srresnet", 20 for "rcan", 1 for "unet"
    , "gc": 32
    , "ng": 2 // 10 for "rcan"
    , "reduction" : 16
    , "act_mode": "R" // "BR" for BN+ReLU | "R" for ReLU
    , "upsample_mode": "convtranspose" // "pixelshuffle" | "convtranspose" | "upconv"
    , "downsample_mode": "strideconv" // "strideconv" | "avgpool" | "maxpool"

    , "init_type": "orthogonal" // "orthogonal" | "normal" | "uniform" | "xavier_normal" | "xavier_uniform" | "kaiming_normal" | "kaiming_uniform"
    , "init_bn_type": "uniform" // "uniform" | "constant"
    , "init_gain": 0.2
  }

  , "train": {
    "G_lossfn_type": "l1" // "l1" | "l2sum" | "l2" | "ssim"
    , "G_lossfn_weight": 1.0

    , "G_optimizer_type": "adam"
    , "G_optimizer_lr": 1e-4
    , "G_optimizer_wd": 0
    , "G_optimizer_clipgrad": null

    , "G_scheduler_type": "MultiStepLR"
    , "G_scheduler_milestones": [100000, 200000, 300000, 400000]
    , "G_scheduler_gamma": 0.5

    , "G_regularizer_orthstep": null
    , "G_regularizer_clipstep": null

    , "checkpoint_test": 5000
    , "checkpoint_save": 5000
    , "checkpoint_print": 200
  }
}

```

**Comment by Zepharchit** [comment]
Thanks for the reply, i was going wrong in the json file itself after looking at the solution that you've provided. Will be modifying the json and will try to train the model.

**Comment by maximagesat** [comment]
Hi, thanks for sharing the .json script. I'm getting this referenced before assignment error, any idea as to the cause?

Traceback (most recent call last):
  File "main_train_usrnet.py", line 242, in <module>
    main()
  File "main_train_usrnet.py", line 149, in main
    for i, train_data in enumerate(train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/KAIR/data/dataset_usrnet.py", line 97, in __getitem__
    img_L = img_L[0::sf, 0::sf, ...]
UnboundLocalError: local variable 'sf' referenced before assignment

**Comment by cszn** [comment]
Check whether `sf ` is assigned properly https://github.com/cszn/KAIR/blob/239c72ecfded5415d7a44a88b81157807ec7b4cc/data/dataset_usrnet.py#L56

**Comment by maximagesat** [comment]
It gets assigned a couple of times before it fails. When it fails, self.count % self.opt['dataloader_batch_size'] = 1

**Comment by cszn** [comment]
@maximagesat  Try to change `sf` to `self.sf`

**Comment by Zepharchit** [comment]
Hi I changed the utilised the json script to run the model but I am getting the following error, please provide direction on how to correct the issue
![Screenshot from 2020-08-31 10-44-54](https://user-images.githubusercontent.com/51807559/91797163-882d8200-ec3f-11ea-97bb-4e9991e005a8.png)

**Comment by cszn** [comment]
Re-download the code and get familiar with the code.

**Comment by Zepharchit** [comment]
Ok thanks

**Comment by cszn** [comment]
@Zepharchit I uploaded the json file, see https://github.com/cszn/KAIR/blob/master/options/train_usrnet.json

**Comment by sherlybe** [comment]
> Ok thanks

hi ,the following error i dont know how to slove? help me! thanks
![image](https://user-images.githubusercontent.com/82870143/124259985-be8aa500-db61-11eb-9ae1-9a9a7d3b26b0.png)

**Comment by UESTCrookieLI** [comment]
> 
> 
> > Ok thanks
> 
> hi ,the following error i dont know how to slove? help me! thanks
> ![image](https://user-images.githubusercontent.com/82870143/124259985-be8aa500-db61-11eb-9ae1-9a9a7d3b26b0.png)
> code is here![image](https://user-images.githubusercontent.com/82870143/124260159-eed24380-db61-11eb-978c-dafecb4cf1ab.png)

hi,I meet the same error.
Do you solve it?
Could you help me?thank you very much!

**Comment by sherlybe** [comment]
> > > Ok thanks
> > 
> > 
> > hi ,the following error i dont know how to slove? help me! thanks
> > ![image](https://user-images.githubusercontent.com/82870143/124259985-be8aa500-db61-11eb-9ae1-9a9a7d3b26b0.png)
> > code is here![image](https://user-images.githubusercontent.com/82870143/124260159-eed24380-db61-11eb-978c-dafecb4cf1ab.png)
> 
> hi,I meet the same error.
> Do you solve it?
> Could you help me?thank you very much!

你把那个self.sf = random.choice（self.sf）替换为self.sf = 1，我是这么做的，不知道你是否可以解决。
You can replace self.sf = random.choice（self.sf）with self.sf = 1, try it, it will be work!
