### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by Gamkiu** [cszn/KAIR#36]
Hello! When I use the msrresnet(getting from the training process,e.g.560000_G.pth) for the test(main_test_msrresnet.py), it occurs an error. But when i use the msrresnet_x4_psnr.pth for the test, there is no errors, how to solve this problem?

![image](https://user-images.githubusercontent.com/26021906/93666455-0a77cc00-fab1-11ea-8978-b2d30837c22e.png)

**Comment by cszn** [comment]
Replace https://github.com/cszn/KAIR/blob/3eb3cc7776fa8c57e8ed7c71bfa8039beb4c6677/main_test_msrresnet.py#L72
by ` sf = 4`
