### ISSUE TITLE
Question regarding the batch normlisation after a convolution

### ISSUE THREAD

**Issue by zaccharieramzi** [cszn/KAIR#4]
In DnCNN, the 2D convolution is followed by a batch normalisation layer.
However, we can see that bias is used in the convolution (https://github.com/cszn/KAIR/blob/master/models/network_dncnn.py#L60-L63). From what I understand, it's important to remove that bias in the case of a convolution followed by a batch normalisation because it will be canceled out.

Is there any reason to keep it?

**Comment by cszn** [comment]
There is no difference between both cases. They will produce the same result.

**Comment by zaccharieramzi** [comment]
Well can't it have some bad effects: https://twitter.com/karpathy/status/1013245864570073090?s=20 ?

**Comment by cszn** [comment]
In my opinion, no.

**Comment by zaccharieramzi** [comment]
Ok fair, then there is no particular reason for keeping it I guess.

Also, I recently sent you an email to ask further questions, have you received it ? (I know it's not related but I don't want to overload the repo with detailed questions)
