### ISSUE TITLE
DatasetUSRNet

### ISSUE THREAD

**Issue by zuenko** [cszn/KAIR#40]
```
20-09-25 03:21:23.915 : <epoch:  5, iter:   5,000, lr:1.000e-04> G_loss: 3.441e-02 
20-09-25 03:21:23.916 : Saving the model.
Traceback (most recent call last):
  File "E:/Work/KAIR/main_train_msrresnet_psnr.py", line 219, in <module>
    main()
  File "E:/Work/KAIR/main_train_msrresnet_psnr.py", line 178, in main
    for test_data in test_loader:
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "D:\anaconda3\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Work\KAIR\data\dataset_usrnet.py", line 116, in __getitem__
    return {'L': img_L, 'H': img_H, 'k': k, 'sigma': noise_level, 'sf': self.sf, 'L_path': L_path, 'H_path': H_path}
AttributeError: 'DatasetUSRNet' object has no attribute 'sf'


Process finished with exit code 1
```

**Comment by ljdongysu** [comment]
I add ```"self.sf = 1```   
``` img_H = img_H[0::self.sf_validation, 0::self.sf_validation, ...] ```
  in file "/KAIR/data/dataset_usrnet.py" line 105, which dosen't matter trianing phase.Maybe it matters test phase!

**Comment by anjemimini** [comment]
Hi, I'm having the same problem. Did you resolve it? Thanks in advance

**Comment by zuenko** [comment]
@anjemimini 
```
class DatasetUSRNet(data.Dataset):
    '''
    # -----------------------------------------
    # Get L/k/sf/sigma for USRNet.
    # Only "paths_H" and kernel is needed, synthesize L on-the-fly.
    # -----------------------------------------
    '''
    def __init__(self, opt):
        super(DatasetUSRNet, self).__init__()
        self.opt = opt
        self.n_channels = opt['n_channels'] if opt['n_channels'] else 3
        self.patch_size = self.opt['H_size'] if self.opt['H_size'] else 96
        self.sigma_max = self.opt['sigma_max'] if self.opt['sigma_max'] is not None else 25
        self.scales = opt['scales'] if opt['scales'] is not None else [1,2,3,4]
        self.sf_validation = opt['sf_validation'] if opt['sf_validation'] is not None else 3
        #self.kernels = hdf5storage.loadmat(os.path.join('kernels', 'kernels_12.mat'))['kernels']
        self.kernels = loadmat(os.path.join('kernels', 'kernels_12.mat'))['kernels']  # for validation

        # -------------------
        # get the path of H
        # -------------------
        self.paths_H = util.get_image_paths(opt['dataroot_H'])  # return None if input is None
        self.count = 0

    def __getitem__(self, index):

        # -------------------
        # get H image
        # -------------------
        H_path = self.paths_H[index]
        img_H = util.imread_uint(H_path, self.n_channels)
        L_path = H_path

        if self.opt['phase'] == 'train':

            # ---------------------------
            # 1) scale factor, ensure each batch only involves one scale factor
            # ---------------------------
            if self.count % self.opt['dataloader_batch_size'] == 0:
                # sf = random.choice([1,2,3,4])
                self.sf = random.choice(self.scales)
                # self.count = 0  # optional
            self.count += 1
            H, W, _ = img_H.shape

            # ----------------------------
            # randomly crop the patch
            # ----------------------------
            rnd_h = random.randint(0, max(0, H - self.patch_size))
            rnd_w = random.randint(0, max(0, W - self.patch_size))
            patch_H = img_H[rnd_h:rnd_h + self.patch_size, rnd_w:rnd_w + self.patch_size, :]

            # ---------------------------
            # augmentation - flip, rotate
            # ---------------------------
            mode = np.random.randint(0, 8)
            patch_H = util.augment_img(patch_H, mode=mode)

            # ---------------------------
            # 2) kernel
            # ---------------------------
            r_value = np.random.randint(0, 8)
            if r_value>3:
                k = utils_deblur.blurkernel_synthesis(h=25)  # motion blur
            else:
                sf_k = random.choice(self.scales)
                k = utils_sisr.gen_kernel(scale_factor=np.array([sf_k, sf_k]))  # Gaussian blur
                mode_k = np.random.randint(0, 8)
                k = util.augment_img(k, mode=mode_k)

            # ---------------------------
            # 3) noise level
            # ---------------------------
            if np.random.randint(0, 8) == 1:
                noise_level = 0/255.0
            else:
                noise_level = np.random.randint(0, self.sigma_max)/255.0

            # ---------------------------
            # Low-quality image
            # ---------------------------
            img_L = ndimage.filters.convolve(patch_H, np.expand_dims(k, axis=2), mode='wrap')
            img_L = img_L[0::self.sf, 0::self.sf, ...]
            # add Gaussian noise
            img_L = util.uint2single(img_L) + np.random.normal(0, noise_level, img_L.shape)
            img_H = patch_H

        else:
            self.sf = self.sf_validation
            k = self.kernels[0, 0].astype(np.float64)  # validation kernel
            k /= np.sum(k)
            noise_level = 0./255.0  # validation noise level
            img_L = ndimage.filters.convolve(img_H, np.expand_dims(k, axis=2), mode='wrap')  # blur
            img_L = img_L[0::self.sf_validation, 0::self.sf_validation, ...]  # downsampling
            img_L = util.uint2single(img_L) + np.random.normal(0, noise_level, img_L.shape)

        k = util.single2tensor3(np.expand_dims(np.float32(k), axis=2))
        img_H, img_L = util.uint2tensor3(img_H), util.single2tensor3(img_L)
        noise_level = torch.FloatTensor([noise_level]).view([1,1,1])

        return {'L': img_L, 'H': img_H, 'k': k, 'sigma': noise_level, 'sf': self.sf, 'L_path': L_path, 'H_path': H_path}

    def __len__(self):
        return len(self.paths_H)
```

**Comment by anjemimini** [comment]
thanks a lot :)

**Comment by UESTCrookieLI** [comment]
> 
> 
> @anjemimini
> 
> ```
> class DatasetUSRNet(data.Dataset):
>     '''
>     # -----------------------------------------
>     # Get L/k/sf/sigma for USRNet.
>     # Only "paths_H" and kernel is needed, synthesize L on-the-fly.
>     # -----------------------------------------
>     '''
>     def __init__(self, opt):
>         super(DatasetUSRNet, self).__init__()
>         self.opt = opt
>         self.n_channels = opt['n_channels'] if opt['n_channels'] else 3
>         self.patch_size = self.opt['H_size'] if self.opt['H_size'] else 96
>         self.sigma_max = self.opt['sigma_max'] if self.opt['sigma_max'] is not None else 25
>         self.scales = opt['scales'] if opt['scales'] is not None else [1,2,3,4]
>         self.sf_validation = opt['sf_validation'] if opt['sf_validation'] is not None else 3
>         #self.kernels = hdf5storage.loadmat(os.path.join('kernels', 'kernels_12.mat'))['kernels']
>         self.kernels = loadmat(os.path.join('kernels', 'kernels_12.mat'))['kernels']  # for validation
> 
>         # -------------------
>         # get the path of H
>         # -------------------
>         self.paths_H = util.get_image_paths(opt['dataroot_H'])  # return None if input is None
>         self.count = 0
> 
>     def __getitem__(self, index):
> 
>         # -------------------
>         # get H image
>         # -------------------
>         H_path = self.paths_H[index]
>         img_H = util.imread_uint(H_path, self.n_channels)
>         L_path = H_path
> 
>         if self.opt['phase'] == 'train':
> 
>             # ---------------------------
>             # 1) scale factor, ensure each batch only involves one scale factor
>             # ---------------------------
>             if self.count % self.opt['dataloader_batch_size'] == 0:
>                 # sf = random.choice([1,2,3,4])
>                 self.sf = random.choice(self.scales)
>                 # self.count = 0  # optional
>             self.count += 1
>             H, W, _ = img_H.shape
> 
>             # ----------------------------
>             # randomly crop the patch
>             # ----------------------------
>             rnd_h = random.randint(0, max(0, H - self.patch_size))
>             rnd_w = random.randint(0, max(0, W - self.patch_size))
>             patch_H = img_H[rnd_h:rnd_h + self.patch_size, rnd_w:rnd_w + self.patch_size, :]
> 
>             # ---------------------------
>             # augmentation - flip, rotate
>             # ---------------------------
>             mode = np.random.randint(0, 8)
>             patch_H = util.augment_img(patch_H, mode=mode)
> 
>             # ---------------------------
>             # 2) kernel
>             # ---------------------------
>             r_value = np.random.randint(0, 8)
>             if r_value>3:
>                 k = utils_deblur.blurkernel_synthesis(h=25)  # motion blur
>             else:
>                 sf_k = random.choice(self.scales)
>                 k = utils_sisr.gen_kernel(scale_factor=np.array([sf_k, sf_k]))  # Gaussian blur
>                 mode_k = np.random.randint(0, 8)
>                 k = util.augment_img(k, mode=mode_k)
> 
>             # ---------------------------
>             # 3) noise level
>             # ---------------------------
>             if np.random.randint(0, 8) == 1:
>                 noise_level = 0/255.0
>             else:
>                 noise_level = np.random.randint(0, self.sigma_max)/255.0
> 
>             # ---------------------------
>             # Low-quality image
>             # ---------------------------
>             img_L = ndimage.filters.convolve(patch_H, np.expand_dims(k, axis=2), mode='wrap')
>             img_L = img_L[0::self.sf, 0::self.sf, ...]
>             # add Gaussian noise
>             img_L = util.uint2single(img_L) + np.random.normal(0, noise_level, img_L.shape)
>             img_H = patch_H
> 
>         else:
>             self.sf = self.sf_validation
>             k = self.kernels[0, 0].astype(np.float64)  # validation kernel
>             k /= np.sum(k)
>             noise_level = 0./255.0  # validation noise level
>             img_L = ndimage.filters.convolve(img_H, np.expand_dims(k, axis=2), mode='wrap')  # blur
>             img_L = img_L[0::self.sf_validation, 0::self.sf_validation, ...]  # downsampling
>             img_L = util.uint2single(img_L) + np.random.normal(0, noise_level, img_L.shape)
> 
>         k = util.single2tensor3(np.expand_dims(np.float32(k), axis=2))
>         img_H, img_L = util.uint2tensor3(img_H), util.single2tensor3(img_L)
>         noise_level = torch.FloatTensor([noise_level]).view([1,1,1])
> 
>         return {'L': img_L, 'H': img_H, 'k': k, 'sigma': noise_level, 'sf': self.sf, 'L_path': L_path, 'H_path': H_path}
> 
>     def __len__(self):
>         return len(self.paths_H)
> ```

Hi，when I use this code, I meet another error--
![图片](https://user-images.githubusercontent.com/55549767/127741843-2c97e4c4-cab3-40c1-bb2a-2e238bb38c3f.png)

could you help me? thank you very much!

**Comment by UESTCrookieLI** [comment]
> 
> 
> Hi, I'm having the same problem. Did you resolve it? Thanks in advance

hi,Do you solve the error?
I replace the code with @anjemimini provided,but i meet another error like this:
![图片](https://user-images.githubusercontent.com/55549767/127742106-6eae587a-ae83-4a96-b45f-c212655a7575.png)

can you help me?
thank you!
