### ISSUE TITLE
I don't have permission to access the model.any idea why?

### ISSUE THREAD

**Issue by marzi9696** [cszn/KAIR#41]

**Comment by better-many-many** [comment]
Hi, I'm having the same problem. Did you resolve it? Thanks in advance

**Comment by marzi9696** [comment]
Hi.
I had this problem like a month ago.honestly I don't remember if I resolves
it or not.
Have you tried using a proxy or a VPN?

**Comment by cszn** [comment]
Now you can download model via https://github.com/cszn/KAIR/blob/master/main_download_pretrained_models.py
