### ISSUE TITLE
Dependencies for USRNet

### ISSUE THREAD

**Issue by anjemimini** [cszn/KAIR#43]
Hi @cszn, where can I find the packages needed to install in order to be able to test and train USRNet? Thanks in advance

**Comment by cszn** [comment]
@anjemimini 
```
pytorch
opencv-python
hdf5storage
matplotlib
```
https://github.com/cszn/USRNet/pull/15/commits/901ad5f4b81de0ae40d135aad3e2fafb6d225ef0

**Comment by anjemimini** [comment]
> @anjemimini
> 
> ```
> pytorch
> opencv-python
> hdf5storage
> matplotlib
> ```
> 
> [cszn/USRNet@901ad5f](https://github.com/cszn/USRNet/commit/901ad5f4b81de0ae40d135aad3e2fafb6d225ef0)
