### ISSUE TITLE
Optimizing DPSR training to avoid low and spiky GPU usage

### ISSUE THREAD

**Issue by aonorgate** [cszn/KAIR#55]
I have the DPSR training running but it does not appear to be fully utilising the GPU which spikes in a saw too profile as below:
![image](https://user-images.githubusercontent.com/60344370/109822120-92e8c400-7c2e-11eb-8585-0cbc75e52c7b.png)

I've tried adjusting the batch size but the change doesn't improve overall GPU utilisation just the profile of the saw tooth.
Overall from the stats and GPU power draw I estimate it is at best hitting about 50% utilization when other GAN training I have done has been able to sustain above 90% when optimised.

Are there any other parameters I should be looking to tweak?

**Comment by lucky-zwx** [comment]
出现了同样的问题！
