### ISSUE TITLE
Hello, what is the noise level of the whole image in USRNet?

### ISSUE THREAD

**Issue by cuiziteng** [cszn/KAIR#59]
Hi ! I found the code in 'main_test_usrnet.py'

Line 94: noise_level_img = 0       # fixed: 0, noise level for LR image
             noise_level_model = noise_level_img  # fixed, noise level of model, default 0

And in your other code, 'USRNet/blob/master/main_test_realapplication.py'
Line 81 noise_level_img = 15       # noise level for LR image, 15 for chip
Line 84 noise_level_img = 2         # noise level for LR image, 0.5~3 for clean images

So what is a reasonable noise level range should I set on a whole degradation image (not chip), I just wonder this question, thx~

**Comment by cszn** [comment]
USRNet is a non-blind method and thus you need to set the noise level.
