### ISSUE TITLE
Could you please upload the pre-tained model to Baidu Netdisk ?

### ISSUE THREAD

**Issue by HaolyShiit** [cszn/KAIR#6]
Hello ! I can not download the Model_Zoo from Google. Could you please upload the pre-tained model to Baidu Netdisk if it's convenient？ Thank you .

**Comment by geyijun** [comment]
only for FFDNet，Baidu Netdisk 
https://pan.baidu.com/s/1lVXrXaGzVNS0-1auLQQIng   （emb3）

**Comment by cszn** [comment]
https://share.weiyun.com/5qO32s3

**Comment by HaolyShiit** [comment]
> https://share.weiyun.com/5qO32s3

Thank you!

**Comment by HaolyShiit** [comment]
> only for FFDNet，Baidu Netdisk
> https://pan.baidu.com/s/1lVXrXaGzVNS0-1auLQQIng （emb3）

Thank you!
