### ISSUE TITLE
test_USRNet error

### ISSUE THREAD

**Issue by Kavit212** [cszn/KAIR#63]
Hi, I have train the USRNet. I am currently trying to test my saved model with main_test_usernet. However, I am getting this error.

LogHandlers setup!
Traceback (most recent call last):
  File "main_test_usrnet.py", line 226, in <module>
    main()
  File "main_test_usrnet.py", line 122, in main
    model.load_state_dict(torch.load(model_path), strict=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for USRNet:
	Missing key(s) in state_dict: "p.m_down1.0.res.1.weight", "p.m_down1.0.res.1.bias", "p.m_down1.0.res.1.running_mean", "p.m_down1.0.res.1.running_var", "p.m_down1.0.res.3.weight", "p.m_down1.1.res.1.weight", "p.m_down1.1.res.1.bias", "p.m_down1.1.res.1.running_mean", "p.m_down1.1.res.1.running_var", "p.m_down1.1.res.3.weight", "p.m_down2.0.res.1.weight", "p.m_down2.0.res.1.bias", "p.m_down2.0.res.1.running_mean", "p.m_down2.0.res.1.running_var", "p.m_down2.0.res.3.weight", "p.m_down2.1.res.1.weight", "p.m_down2.1.res.1.bias", "p.m_down2.1.res.1.running_mean", "p.m_down2.1.res.1.running_var", "p.m_down2.1.res.3.weight", "p.m_down3.0.res.1.weight", "p.m_down3.0.res.1.bias", "p.m_down3.0.res.1.running_mean", "p.m_down3.0.res.1.running_var", "p.m_down3.0.res.3.weight", "p.m_down3.1.res.1.weight", "p.m_down3.1.res.1.bias", "p.m_down3.1.res.1.running_mean", "p.m_down3.1.res.1.running_var", "p.m_down3.1.res.3.weight", "p.m_body.0.res.1.weight", "p.m_body.0.res.1.bias", "p.m_body.0.res.1.running_mean", "p.m_body.0.res.1.running_var", "p.m_body.0.res.3.weight", "p.m_body.1.res.1.weight", "p.m_body.1.res.1.bias", "p.m_body.1.res.1.running_mean", "p.m_body.1.res.1.running_var", "p.m_body.1.res.3.weight", "p.m_up3.1.res.1.weight", "p.m_up3.1.res.1.bias", "p.m_up3.1.res.1.running_mean", "p.m_up3.1.res.1.running_var", "p.m_up3.1.res.3.weight", "p.m_up3.2.res.1.weight", "p.m_up3.2.res.1.bias", "p.m_up3.2.res.1.running_mean", "p.m_up3.2.res.1.running_var", "p.m_up3.2.res.3.weight", "p.m_up2.1.res.1.weight", "p.m_up2.1.res.1.bias", "p.m_up2.1.res.1.running_mean", "p.m_up2.1.res.1.running_var", "p.m_up2.1.res.3.weight", "p.m_up2.2.res.1.weight", "p.m_up2.2.res.1.bias", "p.m_up2.2.res.1.running_mean", "p.m_up2.2.res.1.running_var", "p.m_up2.2.res.3.weight", "p.m_up1.1.res.1.weight", "p.m_up1.1.res.1.bias", "p.m_up1.1.res.1.running_mean", "p.m_up1.1.res.1.running_var", "p.m_up1.1.res.3.weight", "p.m_up1.2.res.1.weight", "p.m_up1.2.res.1.bias", "p.m_up1.2.res.1.running_mean", "p.m_up1.2.res.1.running_var", "p.m_up1.2.res.3.weight". 
	Unexpected key(s) in state_dict: "p.m_down1.0.res.2.weight", "p.m_down1.1.res.2.weight", "p.m_down2.0.res.2.weight", "p.m_down2.1.res.2.weight", "p.m_down3.0.res.2.weight", "p.m_down3.1.res.2.weight", "p.m_body.0.res.2.weight", "p.m_body.1.res.2.weight", "p.m_up3.1.res.2.weight", "p.m_up3.2.res.2.weight", "p.m_up2.1.res.2.weight", "p.m_up2.2.res.2.weight", "p.m_up1.1.res.2.weight", "p.m_up1.2.res.2.weight". 
	size mismatch for p.m_head.weight: copying a param with shape torch.Size([16, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 4, 3, 3]).
	size mismatch for p.m_down1.0.res.0.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for p.m_down1.1.res.0.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for p.m_down1.2.weight: copying a param with shape torch.Size([32, 16, 2, 2]) from checkpoint, the shape in current model is torch.Size([128, 64, 2, 2]).
	size mismatch for p.m_down2.0.res.0.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for p.m_down2.1.res.0.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for p.m_down2.2.weight: copying a param with shape torch.Size([64, 32, 2, 2]) from checkpoint, the shape in current model is torch.Size([256, 128, 2, 2]).
	size mismatch for p.m_down3.0.res.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for p.m_down3.1.res.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for p.m_down3.2.weight: copying a param with shape torch.Size([64, 64, 2, 2]) from checkpoint, the shape in current model is torch.Size([512, 256, 2, 2]).
	size mismatch for p.m_body.0.res.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for p.m_body.1.res.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for p.m_up3.0.weight: copying a param with shape torch.Size([64, 64, 2, 2]) from checkpoint, the shape in current model is torch.Size([512, 256, 2, 2]).
	size mismatch for p.m_up3.1.res.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for p.m_up3.2.res.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for p.m_up2.0.weight: copying a param with shape torch.Size([64, 32, 2, 2]) from checkpoint, the shape in current model is torch.Size([256, 128, 2, 2]).
	size mismatch for p.m_up2.1.res.0.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for p.m_up2.2.res.0.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for p.m_up1.0.weight: copying a param with shape torch.Size([32, 16, 2, 2]) from checkpoint, the shape in current model is torch.Size([128, 64, 2, 2]).
	size mismatch for p.m_up1.1.res.0.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for p.m_up1.2.res.0.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for p.m_tail.weight: copying a param with shape torch.Size([3, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([3, 64, 3, 3]).
	size mismatch for h.mlp.0.weight: copying a param with shape torch.Size([32, 2, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 2, 1, 1]).
	size mismatch for h.mlp.0.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for h.mlp.2.weight: copying a param with shape torch.Size([32, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
	size mismatch for h.mlp.2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for h.mlp.4.weight: copying a param with shape torch.Size([12, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 64, 1, 1]).
	size mismatch for h.mlp.4.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([16]).

It will be great if someone can help me out with this problem.

Thank you

**Comment by cszn** [comment]
Use the defined model https://github.com/cszn/KAIR/blob/bf78bbe0f87f5cabc0e067571a8cb2fa712f7bb6/main_test_usrnet.py#L116
