### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by s0966066980** [cszn/KAIR#67]
![螢幕擷取畫面 2021-06-17 191538](https://user-images.githubusercontent.com/45198905/122386389-6cae2080-cfa0-11eb-9712-bd71a5a16f55.png)

**Comment by cszn** [comment]
https://github.com/cszn/KAIR/blob/9aadcfa6ed27a493ad8b3ed991a2761488773677/main_train_drunet.py#L53
