### ISSUE TITLE
测试如何直接输入模糊分辨率低的图片，然后推理获取结果？

### ISSUE THREAD

**Issue by zsffuture** [cszn/KAIR#68]
如题，我发现作者的test文件测试的图片都是清晰图经过噪声生成低分辨率的图片，然后再通过模型进行超分处理，但是现实中输入的是是模糊图片推理如何做呢？抱歉，小白不是很懂

**Comment by sherlybe** [comment]
> 如题，我发现作者的test文件测试的图片都是清晰图经过噪声生成低分辨率的图片，然后再通过模型进行超分处理，但是现实中输入的是是模糊图片推理如何做呢？抱歉，小白不是很懂

我也在思考这个问题，我理解的是机制不同吧，作者论文说的使用12个模糊核而得到的退化图像，代表了大多数的模糊图像，作者认为这些模糊图像经过模型处理后得到的图像即复原图像。所以你会看到输入的是高清图像，得到的也是高清图像，所以你就会有疑问，作者是做了无用功吗？

**Comment by cszn** [comment]
Please refer to https://github.com/cszn/USRNet/blob/master/main_test_realapplication.py
