### ISSUE TITLE
USRNet Deblurring

### ISSUE THREAD

**Issue by sherlybe** [cszn/KAIR#69]
Hello! I am training USRNet now, and I want to implement the deblurring when s=1 proposed by the author. Can you show me your train_usrnet.json for Deblurring?
Then, when I directly run main_test_usrnet.py and set the scale factor to 1, I get the following results, which are completely ineffective as shown by the author. How to solve this problem?
Hope to get an answer, thanks!
![tiger_x1_k1_usrnet](https://user-images.githubusercontent.com/82870143/123758122-34d4a080-d8f1-11eb-954c-7c7544f822c0.png)
![tiger_x1_k3_LR](https://user-images.githubusercontent.com/82870143/123758128-3605cd80-d8f1-11eb-85c6-6cef7751a3aa.png)

![tiger_x1_k1_LR](https://user-images.githubusercontent.com/82870143/123758102-31d9b000-d8f1-11eb-9b6e-3f7f7165f00b.png)

**Comment by sherlybe** [comment]
another question:I am trying to train usrnet,and the following is my setting
 {
  "task": "usrnet" //  
  , "model": "plain" // "plain" | "gan"
  , "gpu_ids": [0]
  , "scale": 1
  , "n_channels": 3 // 1 for grayscale image restoration, 3 for color image restoration
  , "merge_bn": false
  , "merge_bn_startpoint": 300000

  , "datasets": {
    "train": {
      "name": "train_dataset"
      , "dataset_type": "usrnet"
      , "dataroot_H": "trainsets/trainH"
      , "dataroot_L": null
      , "H_size": 96 // 128 | 192
      , "use_flip": true
      , "use_rot": true
      , "scales": [1]
      , "dataloader_shuffle": true
      , "dataloader_num_workers":2
      , "dataloader_batch_size":16
    }
    , "test": {
      "name": "test_dataset"
      , "dataset_type": "usrnet"
      , "dataroot_H": "testsets/set5"
      , "dataroot_L": null
    }
  }

  , "path": {
    "root": "blur"
    , "pretrained_netG": null
  }
then runing main_train_usrnet.py,it will show the error:
![image](https://user-images.githubusercontent.com/82870143/123759133-32bf1180-d8f2-11eb-96c4-2fc46632bc8c.png)
how to solve it?
thanks!

**Comment by cszn** [comment]
, "model": "plain4"

**Comment by sherlybe** [comment]
> , "model": "plain4"

hi，thanks to your reply. Now I have an urgent question.I strictly follow your steps, and the result is the same as yours, but when performing Deblurring, the result is as follows. why? Can you explain it to me? Looking forward to your reply。
![test_09_x1_k12_LR_LR_x1](https://user-images.githubusercontent.com/82870143/123815980-83059600-d929-11eb-8c06-6c3519fa2872.png)
![test_09_x1_k12_LR_x1_usrnet](https://user-images.githubusercontent.com/82870143/123815996-86991d00-d929-11eb-92bf-8c917b648acc.png)
![test_16_x1_k12_LR_LR_x1](https://user-images.githubusercontent.com/82870143/123816017-8a2ca400-d929-11eb-85b9-b0c54e91e862.png)
![test_16_x1_k12_LR_x1_usrnet](https://user-images.githubusercontent.com/82870143/123816023-8c8efe00-d929-11eb-9756-51748f854809.png)
