### ISSUE TITLE
error calculate_psnr?

### ISSUE THREAD

**Issue by UESTCrookieLI** [cszn/KAIR#72]
```
Traceback (most recent call last):
  File "main_train_usrnet.py", line 230, in <module>
    main()
  File "main_train_usrnet.py", line 213, in main
    current_psnr = util.calculate_psnr(E_img, H_img, border=border)
  File "/home/liziqi/SRcode/KAIR-USRNet/utils/utils_image.py", line 627, in calculate_psnr
    raise ValueError('Input images must have the same dimensions.')
ValueError: Input images must have the same dimensions.
```
I don't how to solve this error?
can some good guy help me out?

**Comment by FYJ10** [comment]
> 
> 
> ```
> Traceback (most recent call last):
>   File "main_train_usrnet.py", line 230, in <module>
>     main()
>   File "main_train_usrnet.py", line 213, in main
>     current_psnr = util.calculate_psnr(E_img, H_img, border=border)
>   File "/home/liziqi/SRcode/KAIR-USRNet/utils/utils_image.py", line 627, in calculate_psnr
>     raise ValueError('Input images must have the same dimensions.')
> ValueError: Input images must have the same dimensions.
> ```
> 
> I don't how to solve this error?
> can some good guy help me out?

I also encountered the same problem. Have you solved it?

**Comment by cszn** [comment]
Solved!
https://github.com/cszn/KAIR/blob/5989e1cd78af7c010b55d8d867daa5686b83299a/data/dataset_usrnet.py#L112

**Comment by Timmate** [comment]
If you ran into a similar issue for Set5 and, most likely in this case, SwinIR, see [this answer](https://github.com/JingyunLiang/SwinIR/issues/39#issuecomment-962533278).
