### ISSUE TITLE
When will you publish the training code of SwinIR?

### ISSUE THREAD

**Issue by z625715875** [cszn/KAIR#73]
Hi,

I found the SwinIR very inspiring and the repo says the training code would be released in this repo. May I ask when the training code is going to be released? Thank you.

Best,
Yang

**Comment by tongchangD** [comment]
插个眼

**Comment by KB-co** [comment]
Looking forward to the release of training code.

**Comment by 781303842** [comment]
插个眼

**Comment by JingyunLiang** [comment]
Thanks for your issue. We have release [the SwinIR training code at KAIR](https://github.com/cszn/KAIR/blob/master/docs/README_SwinIR.md).  We also add an [interactive online Colab demo for real-world image SR](https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb).

**Comment by tongchangD** [comment]
thanks
