### ISSUE TITLE
Training warning:UserWarning

### ISSUE THREAD

**Issue by charlesfish712** [cszn/KAIR#75]
![1](https://user-images.githubusercontent.com/52913351/133212679-72bb5aba-7c30-4aa6-899b-66aa85971eaa.png)
As show in pic.
does it matters?
or something wrong?
and one more thing is that how to prove the training speed

**Comment by cszn** [comment]
It does not influence the training. The userwarning will disappear by changing
https://github.com/cszn/KAIR/blob/a15fd792ebc08d2c9a22fef469c712ec77f42438/models/model_base.py#L62
with 
```
scheduler.step()
```

Two basic ways to improve the training speed:
- Train with DistributedDataParallel for large model
```
python -m torch.distributed.launch --nproc_per_node=8 --master_port=1234 main_train_gan.py --opt options/train_msrresnet_gan.json  --dist True
```
- Improve the dataloader
