### ISSUE TITLE
G_loss is normal?

### ISSUE THREAD

**Issue by wangqi-xxxx** [cszn/KAIR#76]
when i train main_train_psnr.py  by  
python -m torch.distributed.launch --nproc_per_node=4 --master_port=1234 main_train_psnr.py --opt options/train_bsrgan_x4_psnr.json  --dist True

the G_loss is ups and downs，from 2.114e-02  to 1.114e-02 then to 5.6e-02，is normal？

**Comment by wangqi-xxxx** [comment]
- 
![微信图片_20210916134921](https://user-images.githubusercontent.com/9344624/133556935-34118b99-453a-4e0f-a48f-d77cbea22f5c.png)

**Comment by cszn** [comment]
It is normal since the degradation degrees of patches in different batches could be quite different.
