### ISSUE TITLE
could not find MARK

### ISSUE THREAD

**Issue by betterftr** [cszn/KAIR#77]
Cant test my model, pls haalp
python main_test_swinir.py --task real_sr --scale 4 --model_path /superresolution/swinir_sr_realworld_x4_gan/models/345500_G.pth --folder_lq testsets/asd
downloading model /superresolution/swinir_sr_realworld_x4_gan/models/345500_G.pth.pth
Traceback (most recent call last):
  File "main_test_swinir.py", line 253, in <module>
    main()
  File "main_test_swinir.py", line 42, in main
    model = define_model(args)
  File "main_test_swinir.py", line 175, in define_model
    pretrained_model = torch.load(args.model_path)
  File "D:\CONDA\envs\real\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\CONDA\envs\real\lib\site-packages\torch\serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

**Comment by JingyunLiang** [comment]
From "downloading model /superresolution/swinir_sr_realworld_x4_gan/models/345500_G.pth.pth", we can see that the `model_path` is invalid. Please make sure that `/superresolution/swinir_sr_realworld_x4_gan/models/345500_G.pth` exists. If not, `main_test_swinir.py` will try to download it from official pretrained model zoo.
https://github.com/cszn/KAIR/blob/d749c244818501dfdd94b7c29378400ea3b3f788/main_test_swinir.py#L33

**Comment by cszn** [comment]
`345500_G.pth` or `345000_G.pth`? You should also try to test `345000_E.pth` which is supposed to have a better performance.

**Comment by betterftr** [comment]
thank you, full path worked!
