### ISSUE TITLE
gan_type selection for SwinIR

### ISSUE THREAD

**Issue by richardburleigh** [cszn/KAIR#79]
Thank you for this great project!

I see that the configuration for SwinIR has the standard "gan_type" set to "gan", rather than any of the other GANs available.

I understand there are some advantages in the other GAN types, such as lsgan, so I'm curious if there is a reason why they are not used by default?

I'd love to test them all, but my poor 2x 2080ti rig would take all month to converge on all 5 of them :-)

**Comment by cszn** [comment]
https://github.com/cszn/KAIR/blob/e7e2cc2940d4900f7aaf46824a8c16934d073871/options/train_bsrgan_x4_gan.json#L88-L89

You can also use `lsgan` with weight `1` to get similar results.

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
