### ISSUE TITLE
Potential bug in main_train_dncnn.py and dataset_dncnn.py?

### ISSUE THREAD

**Issue by HolmesShuan** [cszn/KAIR#80]
https://github.com/cszn/KAIR/blob/e7e2cc2940d4900f7aaf46824a8c16934d073871/main_train_dncnn.py#L112-L114
Note that `dataset_opt` refers to `opt['datasets']['train']` and it will be used in 

https://github.com/cszn/KAIR/blob/e7e2cc2940d4900f7aaf46824a8c16934d073871/data/dataset_dncnn.py#L19-L26

However, according to [train_dncnn.json](https://github.com/cszn/KAIR/blob/master/options/train_dncnn.json), 
https://github.com/cszn/KAIR/blob/e7e2cc2940d4900f7aaf46824a8c16934d073871/options/train_dncnn.json#L6-L20

`n_channels`, `sigma` and `sigma_test` are defined as `opt['n_channels']`, `opt['sigma']` and `opt['sigma_test']` instead of `opt['train']['n_channels']`, `opt['train']['sigma']` and `opt['train']['sigma_test']` ,which makes 
```python
self.n_channels = opt['n_channels'] if opt['n_channels'] else 3 
self.patch_size = opt['H_size'] if opt['H_size'] else 64 
self.sigma = opt['sigma'] if opt['sigma'] else 25 
self.sigma_test = opt['sigma_test'] if opt['sigma_test'] else self.sigma 
```
become
```python
self.n_channels = 3 
self.patch_size = opt['H_size'] if opt['H_size'] else 64 
self.sigma = 25 
self.sigma_test = self.sigma 
```

Similar issues can also be found in `main_train_drunet.py`.

**Comment by cszn** [comment]
Fixed now!

https://github.com/cszn/KAIR/blob/c755c73a8123aaa06ad22420dbe9856d7e2b1f75/utils/utils_option.py#L58-L59

https://github.com/cszn/KAIR/blob/c755c73a8123aaa06ad22420dbe9856d7e2b1f75/utils/utils_option.py#L86
https://github.com/cszn/KAIR/blob/c755c73a8123aaa06ad22420dbe9856d7e2b1f75/options/train_dncnn.json#L25-L26
