### ISSUE TITLE
trainset

### ISSUE THREAD

**Issue by ConanMusk** [cszn/KAIR#81]
![2021-09-22 11-59-03屏幕截图](https://user-images.githubusercontent.com/67884112/134281549-8ca76fff-d9ad-4ded-a149-2a9567fea7ca.png)
![2021-09-22 11-57-56屏幕截图](https://user-images.githubusercontent.com/67884112/134281557-70ca1e55-0bd8-46b2-85c3-2205302f5426.png)

![2021-09-22 12-03-09屏幕截图](https://user-images.githubusercontent.com/67884112/134281690-3a710fba-ceb9-4757-895d-8c653ae4b585.png)
这个文件夹的目录结构是什么？

**Comment by JingyunLiang** [comment]
File structures are like `./trainsets/DIV2K/HR/*.png` (for HR path) and `./trainsets/DIV2K/LR_bicubic/X4/*.png` (for LR path). Just modify `traininsets/trainH` and  `traininsets/trainL` in json file to `trainsets/DIV2K/HR` and `trainsets/DIV2K/LR_bicubic/X4`.

**Comment by ConanMusk** [comment]
你们进行实验的pytorch版本是什么

**Comment by JingyunLiang** [comment]
Pytorch 1.7.1

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
