### ISSUE TITLE
Training Files??

### ISSUE THREAD

**Issue by edwardcho** [cszn/KAIR#91]
Hello Sir.

I had tried to train and test your code.
I don't know that  I could't match source codes for training/test .

                      training                          test
USRNet,        main_train_usrnet.py      main_test_usrnet.py
DnCNN,        main_train_dncnn.py      main_test_dncnn.py
FFDNet,         ? (I don't know)              main_test_ffdnet.py
SRMD,           ?                                      main_test_srmd.py
DPSR,            ?                                      main_test_dpsr.py
MSRResNet,  ?                                      ?
ESRGAN,        ?                                     ?
BSRGAN,        ?                                     main_test_bsrgan.py
SwinIR            ?                                     main_test_swinir.py

Thanks,
Edward Cho

**Comment by jxtps** [comment]
For SwinIR, see: https://github.com/cszn/KAIR/blob/master/docs/README_SwinIR.md
