### ISSUE TITLE
Questions about training setup of SwinIR

### ISSUE THREAD

**Issue by blackcow** [cszn/KAIR#93]
Seeing that you set the "window_size" = 8 by default training,  I'm curious what happens if you set it to a larger window size (e.g. 12 or 24) and whether it results in a PSNR improvement ?

Looking forward to your reply : )

**Comment by JingyunLiang** [comment]
I think it may improve the performance if the head_dim is large enough as well, but the computation and memory complexity rises quadratically with window size.

**Comment by blackcow** [comment]
> I think it may improve the performance if the head_dim is large enough as well, but the computation and memory complexity rises quadratically with window size.

Thank you for your reply！

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
