### ISSUE TITLE
SwinIR: Inconsistent image dimension when calculating PSNR

### ISSUE THREAD

**Issue by R0n12** [cszn/KAIR#95]
I met this following error when testing swinIR using Set5 dataset

![image](https://user-images.githubusercontent.com/59843980/139747520-94918f33-bd29-4e60-bca9-85249570de50.png)

This is my data path configuration:

![image](https://user-images.githubusercontent.com/59843980/139747717-425cb5dd-e523-44e0-8fc5-695d044914ba.png)

I noticed that the error was caused by that the Set5 HR images are not exactly 2x scaled up from Set5 bicubic2x images.
For example, the baby.png in LRbicx2 is 252x252x3 whereas in Original, it is 512x512x3. After feeding through the network, the estimated image is 504x504x3 which is inconsistent with 512x512x3 for calculating PSNR.

Do you have any idea about this issue in Set5? I downloaded the dataset from the link you provided.

Greatly appreciate your help and your work.

**Comment by Quentin-Anthony** [comment]
It appears that the Set5 images from the SwinIR google drive (https://drive.google.com/drive/folders/1B3DJGQKB6eNdwuQIhdskA64qUuVKLZ9u) are the wrong sizes?
```
[KAIR/testsets/Set5/LRbicx2]$ file *
baby.png:      PNG image data, 252 x 252, 8-bit/color RGB, non-interlaced
bird.png:      PNG image data, 144 x 144, 8-bit/color RGB, non-interlaced
butterfly.png: PNG image data, 126 x 126, 8-bit/color RGB, non-interlaced
head.png:      PNG image data, 138 x 138, 8-bit/color RGB, non-interlaced
woman.png:     PNG image data, 114 x 168, 8-bit/color RGB, non-interlaced
```

Whereas the SwinIR repo's Set5 (https://github.com/JingyunLiang/SwinIR/tree/main/testsets/Set5) have the correct dimensions and work fine when passed to KAIR:

```
[SwinIR/testsets/Set5/LR_bicubic/X2]$ file *
babyx2.png:      PNG image data, 256 x 256, 8-bit/color RGB, non-interlaced
birdx2.png:      PNG image data, 144 x 144, 8-bit/color RGB, non-interlaced
butterflyx2.png: PNG image data, 128 x 128, 8-bit/color RGB, non-interlaced
headx2.png:      PNG image data, 140 x 140, 8-bit/color RGB, non-interlaced
womanx2.png:     PNG image data, 114 x 172, 8-bit/color RGB, non-interlaced
```

**Comment by JingyunLiang** [comment]
@Quentin-Anthony Thank you very much! I didn't notice the difference.

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.

**Comment by JAYCHOU2020** [comment]
> Feel free to open it if you have more questions.

when i use DIV2K to train ,i also meet this error:(352, 512, 3) (338, 510, 3)

 raise ValueError('Input images must have the same dimensions.')
ValueError: Input images must have the same dimensions.
