### ISSUE TITLE
Question about the not-square 'attn'

### ISSUE THREAD

**Issue by blackcow** [cszn/KAIR#96]
https://github.com/cszn/KAIR/blob/a4497b818e322193f8517a6ec0effde0717df252/models/network_swinir.py#L130

How to generate 'relative_position_bias' & 'relative_position_bias_table' correctly when 'attn' is a non-square matrix ?

When the dimensions of Q, K are not the same (i.e., N_q is not equal to N_k), the generated 'attn' is non-square, so I resize the relative_position_bias_table. I tried, but the relative_position_bias does not work as expected. After training, the PSNR does not change at test time even without the 'relative_position_bias' : ( 

How should I generate relative_position_bias for this case? Looking forward to your reply : )

**Comment by JingyunLiang** [comment]
I think you cannot simply resize the position encoding as it is a relative encoding. Modify the `relative_position_index` at https://github.com/cszn/KAIR/blob/a4497b818e322193f8517a6ec0effde0717df252/models/network_swinir.py#L93

and change the size of  `relative_position_bias_table` at
https://github.com/cszn/KAIR/blob/a4497b818e322193f8517a6ec0effde0717df252/models/network_swinir.py#L90
